version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./www/:/var/www/
    container_name: proxy
    depends_on:
      - api
  api:
    image: kikiki0611/shorten-app:latest
    ports:
      - "8080:8080"
    container_name: api