spring:
  application:
    name: home-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    database: mysql
    defer-datasource-initialization: true

server:
  tomcat:
    max-threads: 80