version: "3.3"

services:
  proxy:
    container_name: proxy
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./appdata/conf.d:/etc/nginx/conf.d
      - ./appdata/certbot/conf:/etc/letsencrypt
      - ./appdata/certbot/data:/var/www/certbot
      - ./www/:/var/www/
#    depends_on:
#      - api
    networks:
      - our_net

#  api:
#    container_name: api
#    image: kikiki0611/shorten-app:latest
#    restart: unless-stopped
#    networks:
#      - our_net

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email kikiki0611@gmail.com --agree-tos --no-eff-email -d tight.ga
    volumes:
      - ./appdata/certbot/conf:/etc/letsencrypt
      - ./appdata/certbot/logs:/var/log/letsencrypt
      - ./appdata/certbot/data:/var/www/certbot
    depends_on:
      - proxy

networks:
  our_net:
    driver: bridge